# Generated by Django 5.0.6 on 2024-06-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_year', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('DRAMA', 'Drama'), ('COMEDY', 'Comedy'), ('HORROR', 'Horror'), ('ROMANCE', 'Romance')], max_length=50)),
                ('watched', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
